---
title: "Analyse énergétique"
author: "Wissem Lamouchi"
date: "2025-10-25"
output:
  html_document:
    toc: true
    toc_depth: 2c
    fig_caption: true
---

{r setup, include=FALSE}
# Paramètres globaux pour le document
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Charger les packages nécessaires
library(shiny)
library(ggplot2)
library(dplyr)
library(bslib)

# Donnée du fichier csv, charger à partir du lien csv du GitHub

Data = read.csv("https://raw.githubusercontent.com/bymatzo/SAE-R/refs/heads/main/data/data.csv", sep =",", dec = ".")



#Introduction 

  Dans un contexte de transition énergétique et de lutte contre le réchauffement climatique, la performance énergétique des logements constitue un enjeu majeur.
Les politiques publiques encouragent de plus en plus la rénovation thermique et la réduction des émissions de CO₂ issues du secteur résidentiel.
Dans cette optique, ce rapport vise à étudier l’impact du type d’énergie de chauffage sur la performance énergétique des logements du département du Rhône.

#Problématique 

  "Les logements du département du Rhône chauffés à l’électricité présentent-ils de meilleures performances énergétiques et des émissions de CO₂ plus faibles que ceux utilisant le gaz ou le fioul ?"
  
